[package]
name = "game-shared"
edition.workspace = true
authors.workspace = true
version.workspace = true
description = "Shared protocol, components, and gameplay data for Mira Game"

[dependencies]
bevy.workspace = true
lightyear.workspace = true
polyanya.workspace = true
polyanya-glam.workspace = true
serde.workspace = true

[dev-dependencies]
serde_json.workspace = true
