[services]
api_base_url = "http://localhost:8080"
live_api_base_url = "http://localhost:8082"
matchmaking_api_base_url = "http://localhost:8083"
champion_api_base_url = "http://localhost:8084"
chat_api_base_url = "http://localhost:8085"

[keycloak]
base_url = "http://localhost:8081"
realm = "mira"
client_id = "mira-bevy"
password_client_id = "mira-e2e"
